# Generated by Django 2.0 on 2017-12-20 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
                ('promotion', models.CharField(default='', max_length=100)),
                ('webpage', models.URLField(default='')),
                ('phone', models.IntegerField(default=0)),
            ],
        ),
    ]
