# Generated by Django 2.0 on 2018-01-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2cprofile',
            name='category',
            field=models.CharField(choices=[('sf', 'science fiction'), ('dr', 'drama'), ('ft', 'fantasy'), ('bg', 'biography'), ('ht', 'history'), ('ot', 'others')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
