# Generated by Django 2.0 on 2018-01-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_b2cprofile_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2cprofile',
            name='category',
            field=models.CharField(choices=[('science fiction', 'science fiction'), ('drama', 'drama'), ('fantasy', 'fantasy'), ('biography', 'biography'), ('history', 'history'), ('others', 'others')], max_length=50),
        ),
    ]
