# Generated by Django 2.0.1 on 2018-01-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20180105_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2cprofile',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='b2cprofile',
            name='category',
            field=models.CharField(choices=[('Comida y Bebida', 'Comida y Bebida'), ('Salud y Bienestar', 'Salud y Bienestar'), ('Ropa y Accesorios', 'Ropa y Accesorios'), ('Energía', 'Energía'), ('Arte', 'Arte'), ('Artículos para el Hogar', 'Aartículos para el Hogar'), ('Artículos para Oficina', 'Artículos para Oficina'), ('Atículos Electrónicos', 'Artículos Electrónicos'), ('Juguetes', 'Juguetes'), ('Automóviles', 'Automóviles'), ('Ventas al por Menor', 'Ventas al por Menor'), ('Libros', 'Libros'), ('Serivicios Publicitarios', 'Servicios Publicitarios'), ('Cosmética y Cuidado Personal', 'Cosmética y Cuidado Personal'), ('Artículos Deportivos', 'Artículos Deportivos'), ('Servicios de Limpieza', 'Sercicios de Limpieza'), ('Ventas al por Mayor', 'Ventas al por Mayor'), ('Servicios Empresariales', 'Servicios Empresariales'), ('Servicios de Paquetería', 'Servicios de Paquetería'), ('Servicios Financieros', 'Servicios Financieros'), ('Servicios Bancarios', 'Servicios Bancarios'), ('Organización de Eventos', 'Organizaciónde de Eventos')], max_length=50),
        ),
    ]
